ref:
  SPECIES :  "homo_sapiens" 
  REF_DATATYPE : "dna"            # [cdna,cds, dna, ncrna, pep]
  REF_BUILD : "GRCh38"            # GRCh38 or GRCh37 spec = BUILD (converts build into string depending on 37 or 38)
  REF_RELEASE :  "release-110"