ref:
  SPECIES :  "homo_sapiens" 
  DATATYPE : "dna"            # [cdna,cds, dna, ncrna, pep]
  BUILD : "GRCh38"            # GRCh38 or GRCh37 spec = BUILD (converts build into string depending on 37 or 38)
  RELEASE :  "110"

machine_type:
  small_cpu :
    name : "e2-standard-8"
  med_cpu :
    name : "e2-standard-8"
  high_cpu : 
    name : "e2-standard-8"
  high_mem : 
    name : "n1-highmem-32"

log_dir: "logs"
